
[env]
TERM = "xterm-256color"

[window]
padding = { x = 20, y = 35 }
dimensions = { columns = 60, lines = 20 }
position = { x = 670, y = 340 }

decorations = "Transparent"

opacity = 1
blur = true

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 20

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
